# Generated by Django 5.2.8 on 2025-11-23 20:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão social')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('tema', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tema')),
                ('exclusoes_padrao', models.TextField(blank=True, null=True, verbose_name='Exclusões padrão')),
                ('declaracoes_padrao', models.TextField(blank=True, null=True, verbose_name='Declarações padrão')),
                ('termo_confidencialidade_padrao', models.TextField(blank=True, null=True, verbose_name='Termo de confidencialidade padrão')),
                ('prazo_inicio_padrao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prazo de início padrão')),
                ('prazo_entrega_padrao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prazo de entrega padrão')),
                ('agradecimentos_padrao', models.TextField(blank=True, null=True, verbose_name='Agradecimentos padrão')),
                ('papel_timbrado', models.FileField(blank=True, null=True, upload_to='papel_timbrado/', verbose_name='Papel timbrado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome do cliente / Nome fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão social')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do contato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True, verbose_name='UF')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('is_cliente', models.BooleanField(default=True, verbose_name='Cliente')),
                ('is_fornecedor', models.BooleanField(default=False, verbose_name='Fornecedor')),
                ('is_parceiro', models.BooleanField(default=False, verbose_name='Parceiro')),
                ('is_funcionario', models.BooleanField(default=False, verbose_name='Funcionário')),
                ('is_responsavel_tecnico', models.BooleanField(default=False, verbose_name='Responsável técnico')),
                ('is_outro', models.BooleanField(default=False, verbose_name='Outros')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_servico', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoria de serviço',
                'verbose_name_plural': 'Categorias de serviço',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('owner', 'Administrador / Proprietário'), ('normal', 'Usuário padrão')], default='normal', max_length=20, verbose_name='Tipo de usuário')),
                ('can_manage_contatos', models.BooleanField(default=True, verbose_name='Pode gerenciar contatos')),
                ('can_manage_servicos', models.BooleanField(default=True, verbose_name='Pode gerenciar serviços')),
                ('can_manage_definicoes', models.BooleanField(default=False, verbose_name='Pode alterar definições da empresa')),
                ('can_manage_propostas_definicoes', models.BooleanField(default=False, verbose_name='Pode alterar definições de propostas')),
                ('can_manage_propostas', models.BooleanField(default=False, verbose_name='Pode gerenciar propostas')),
                ('can_manage_usuarios', models.BooleanField(default=False, verbose_name='Pode gerenciar usuários')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PropostaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusoes', models.TextField(blank=True, verbose_name='Exclusões')),
                ('declaracoes', models.TextField(blank=True, verbose_name='Declarações')),
                ('termo_confi', models.TextField(blank=True, verbose_name='Termo de confidencialidade')),
                ('agradecimentos', models.TextField(blank=True, verbose_name='Agradecimentos')),
                ('prazo_inicio', models.CharField(blank=True, verbose_name='Prazo para início dos serviços')),
                ('prazo_entrega', models.CharField(blank=True, verbose_name='Prazo para entrega dos serviços')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposta_config', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Definições de propostas',
                'verbose_name_plural': 'Definições de propostas',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do serviço')),
                ('entregaveis', models.TextField(blank=True, null=True, verbose_name='Entregáveis')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor padrão sugerido nas propostas (editável lá).', max_digits=12, null=True, verbose_name='Valor padrão')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='core.categoriaservico', verbose_name='Categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['descricao'],
            },
        ),
    ]
