# Generated by Django 5.2.8 on 2025-12-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaconfiguracao',
            name='papel_timbrado',
            field=models.FileField(blank=True, null=True, upload_to='propostas/papel_timbrado/'),
        ),
    ]
