# Generated by Django 5.2.8 on 2025-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_propostaconfiguracao_papel_timbrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaconfiguracao',
            name='margem_direita',
            field=models.DecimalField(decimal_places=1, default=15.0, help_text='Margem direita do texto no PDF (mm).', max_digits=5),
        ),
        migrations.AddField(
            model_name='propostaconfiguracao',
            name='margem_esquerda',
            field=models.DecimalField(decimal_places=1, default=15.0, help_text='Margem esquerda do texto no PDF (mm).', max_digits=5),
        ),
        migrations.AddField(
            model_name='propostaconfiguracao',
            name='margem_inferior',
            field=models.DecimalField(decimal_places=1, default=20.0, help_text='Margem inferior do texto no PDF (mm).', max_digits=5),
        ),
        migrations.AddField(
            model_name='propostaconfiguracao',
            name='margem_superior',
            field=models.DecimalField(decimal_places=1, default=20.0, help_text='Margem superior do texto no PDF (mm).', max_digits=5),
        ),
    ]
