# Generated by Django 5.2.8 on 2025-12-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_propostaconfiguracao_margem_direita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaconfiguracao',
            name='numero_auto_iniciar',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propostaconfiguracao',
            name='padrao_numero',
            field=models.CharField(blank=True, help_text='Use {numero}, {dia}, {mes}, {ano}, {horario}. Ex.: PRO_{numero}_{mes}{ano}', max_length=255),
        ),
    ]
