# Generated by Django 5.2.8 on 2025-12-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_propostaconfiguracao_numero_auto_iniciar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propostaconfiguracao',
            name='padrao_numero',
        ),
        migrations.AddField(
            model_name='propostaconfiguracao',
            name='numero_config',
            field=models.JSONField(blank=True, help_text='Configuração visual de numeração automática (lista de linhas com prefixo, parâmetro e sufixo).', null=True),
        ),
        migrations.AlterField(
            model_name='propostaconfiguracao',
            name='numero_auto_iniciar',
            field=models.IntegerField(default=1, help_text='Valor inicial do contador automático de propostas.'),
        ),
    ]
