# Generated by Django 5.2.8 on 2025-11-23 21:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captacoes', to='core.empresa')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('company', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('titulo_servico', models.CharField(max_length=180)),
                ('data_servico', models.DateField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em andamento'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20)),
                ('cep', models.CharField(blank=True, max_length=15)),
                ('logradouro', models.CharField(blank=True, max_length=160)),
                ('numero_end', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=160)),
                ('itens', models.JSONField(blank=True, default=list)),
                ('parcelas', models.JSONField(blank=True, default=list)),
                ('desconto_modo', models.CharField(choices=[('valor', 'Valor fixo'), ('percentual', 'Percentual')], default='valor', max_length=12)),
                ('desconto_input', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('desconto_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('exibir_apenas_total', models.BooleanField(default=False)),
                ('objetivo_texto', models.TextField(blank=True, default='')),
                ('exclusos_texto', models.TextField(blank=True, default='')),
                ('declaracoes_texto', models.TextField(blank=True, default='')),
                ('confidencialidade_texto', models.TextField(blank=True, default='')),
                ('assinatura_texto', models.TextField(blank=True, default='')),
                ('prazo_inicio_texto', models.TextField(blank=True, default='')),
                ('prazo_entrega_texto', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='propostas.captacao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='core.contato')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='core.empresa')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'numero')},
            },
        ),
    ]
