# Generated by Django 5.2.8 on 2025-12-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='escopo_texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposta',
            name='investimentos_texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
