# Generated by Django 5.2.8 on 2025-12-09 02:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0002_proposta_escopo_texto_proposta_investimentos_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='permitir_acesso_publico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='public_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='rejeitado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='revisao_mensagem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposta',
            name='revisao_solicitada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
