# Generated by Django 5.2.8 on 2025-12-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0003_proposta_aprovado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='modelo_proprio_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='propostas/modelos_proprios/', verbose_name='Modelo próprio de proposta'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='usar_modelo_sistema',
            field=models.BooleanField(default=True),
        ),
    ]
