# Generated by Django 5.2.8 on 2025-12-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0004_proposta_modelo_proprio_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='sequencia_int',
            field=models.PositiveIntegerField(blank=True, help_text='Sequência interna de numeração por empresa (1, 2, 3...).', null=True),
        ),
    ]
